name: Web Page Snapshot

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule daily at midnight UTC
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # paths:
    #   - '**/androidITPStoreSnapshot.yml'
jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install puppeteer

    - name: Take Web Page Snapshot
      run: node snapshot.js

    - name: Upload Snapshot to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-page-snapshot
        path: snapshot.png
